<div>
	<div style='text-align: center;' >
		<img style='width: 100%;' src='<?=$img?>/img/panel.png' />
	</div>
	<div>
		<label style='<?=$style?>' >Estimados,<br/>
		Se recibió un nuevo correo electrónico con los siguientes datos:<br/>
		Nombres:</label><br/>
		<label style='<?=$styleB?>' > <?=$fullname?> </label><br/>
		<label style='<?=$style?>' >Correo Electrónico :</label><br/>
		<label style='<?=$styleB?>' > <?=$email?> </label><br/>
		<label style='<?=$style?>' >Mensaje :</label><br/>
		<label style='<?=$styleB?>' > <?=$message?> </label><br/>
	</div>
	<div style="margin-top:1em;">
		<label style='<?=$style?>' > <?=date('Y-m-d H:i:s')?></label>
	</div>
</div>